### ISSUE TITLE
✨ feat: 추천책 페이지 관련 기능 추가 

### ISSUE THREAD

**Issue by seul-dev** [Team-Seollem/seollem-fe#106]
### 📌 작업 내용
- 추천책 페이지의 경우 서버에서 외부 api(알라딘)의 데이터를 가져오기 때문에 데이터를 가져오는 속도가 느려서 이 부분에 react-query의 prefetch 기능을 추가해서 개선을 진행할 예정

### ✅ Todo
- [x] 추천책 페이지 prefetch 적용 
- [x] stale time 적용(알라딘 api 데이터가 바뀌지 않기 때문에)
- [x] (ui)선택된 탭 ui 추가
