### ISSUE TITLE
🔧 config: 프로젝트 초기 환경 설정  

### ISSUE THREAD

**Issue by seul-dev** [Team-Seollem/seollem-fe#2]
### 📌 작업 내용

- 프로젝트 진행에 필요한 초기환경 설정

### ✅ Todo

- [x] vite 프로젝트 생성 (react-ts)
- [x] ES Lint
- [x] Prettier 
- [x] husky(git hook 자동화) 
- [x] 프로젝트에 사용하는 라이브러리 설치(styled components, react-router-dom, recoil, axios, react-query 
- [x] 절대경로 설정
- [x]  issue template 
- [x] pr template

**Comment by seul-dev** [comment]
초기 환경 설정을 빠르게 진행하기 위해서 main branch에서 작업했습니다. 
다음 이슈부터는 브랜치 전략을 잘 지키겠습니다.
